
[functions.amadeus-oaut-token]
enabled = true
verify_jwt = true
import_map = "./functions/amadeus-oaut-token/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/amadeus-oaut-token/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/amadeus-oaut-token/*.html" ]

[functions.validate-flight]
enabled = true
verify_jwt = true
import_map = "./functions/validate-flight/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/validate-flight/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/validate-flight/*.html" ]

[functions.amadeus-flights]
enabled = true
verify_jwt = true
import_map = "./functions/amadeus-flights/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/amadeus-flights/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/amadeus-flights/*.html" ]
